In [1]:
import numpy as np
import math
np.set_printoptions(precision=3)

def display_init (X, Y, layer_dims, m, learning_rate, no_iter, W, b):
    print ('--------------------------------------')
#     print ('Inputs per sample = {}'.format(layer_dims[0]))
#     print ('Number of samples = {}'.format(m))
#     print ('Outputs per sample = {}'.format(layer_dims[-1]))
#     print ('Number of hidden layers = {}'.format(len(layer_dims)-2))
#     print ('Number of units in each layer = {}'.format(layer_dims))
#     print ('Learning rate = {}'.format(learning_rate))
#     print ('Number of iterations = {}'.format(no_iter))
#     print ('Input matrix X[{}x{}] =\n {}'.format(layer_dims[0], m, X))
    print ('Desired output matrix Y[{}x{}] =\n {}'.format(layer_dims[-1], m, Y))
#     print ('Initial weights W =\n')
#     [print ('W[{}] {} = {},\n'.format(i, W[i].shape, W[i])) for i in range (len(layer_dims)-1)]
#     print ('Initial biases b =\n')
#     [print ('b[{}] {} = {},\n'.format(i, b[i].shape, b[i])) for i in range (len(layer_dims)-1)]
    print ('--------------------------------------')

def test_init():
    X = np.array([[0.05], [0.10]])      # Inputs
    W = np.array([[[0.15,0.20], [0.25,0.30]],[[0.40,0.45], [0.50,0.55]]])
    b = np.array([[0.35],[0.60]])
    Y = np.array([[0.01], [0.99]])      # Desired output
    return(X,W,b,Y)

def initialize_param(layer_dims):
    W = []
    b = []
    for i in range(1,len(layer_dims)):
        tmp = np.random.randn(layer_dims[i],layer_dims[i-1])*0.01
        W.append(np.random.randn(layer_dims[i],layer_dims[i-1])*0.01)
        b.append(np.zeros((layer_dims[i],1)))
    return (W,b)

def activation(act_type, z):
    if act_type == 'sigmoid':
        return(1/(1 + np.exp(-z)))
    elif act_type == 'relu':
        return(np.maximum(z, 0))

def forward_prop(X, W, b, Y, layers):
    Z = []
    A = []
    Z_prev = X
    for l in range(layers):     # Computing Z & A across each layer & storing the results in a list
        Z.append(np.dot(W[l],Z_prev)+b[l])
        A.append(activation('sigmoid',Z[l]))
        Z_prev = A[l]
    Z = np.array(Z)
    A = np.array(A)
    return(Z,A)

def cost_func (AL, Y, m, cf_type):
    if (cf_type == 'cross_entropy'):
        cost = (-1 / m) * np.sum(np.multiply(Y,np.log(AL)) + np.multiply((1-Y),np.log(1-AL)))
        cost = np.squeeze(cost)
    elif (cf_type == 'sq_err'):
        cost = np.sum(1/2*np.square(Y - AL))
    return(cost)

        
def cost_func_cross_entropy (AL,Y,m):
    cost = (-1 / m) * np.sum(np.multiply(Y,np.log(AL)) + np.multiply((1-Y),np.log(1-AL)))
    cost = np.squeeze(cost)
    return(cost)

def cost_func_sq_err (AL,Y,m):
    cost = np.sum(1/2*np.square(Y - AL))
    return(cost)

def back_prop(A,Y,m,layers):
    dZ = []
    dW = []
    db = []
    dZ.insert(0,np.array(A[-1]-Y))
    dW.insert(0,(1 / m)*np.dot(dZ[0],A[-2].T))
    db.insert(0,(1 / m)*np.sum(dZ[0], axis=1, keepdims=True))
    for l in range(layers-2,-1,-1):
#         dZ.insert(0,np.dot(dW[0].T,dZ[0])*(A[l-1]*(1-A[l-1])))
        dZ_tmp1 = np.dot(dW[0].T,dZ[0])
        dZ_tmp2 = np.dot(A[l-1].T,(1-A[l-1]))
        dZ.insert(0,np.dot(dZ_tmp1, dZ_tmp2))
        dW.insert(0,np.dot(dZ[0],A[l-1].T))
        db.insert(0,(1 / m)*np.sum(dZ[0], axis=1, keepdims=True))
    return(dW, db)    
        
def adjust_weights_bias(W, b, dW, db, learning_rate):
    W = W - np.multiply(learning_rate,dW)
    b = b - np.multiply(learning_rate,db)
    return (W, b)
    
def main():
    ##### Initialize Neural Network #####
    np.random.seed(3)
    layer_dims = [2,5,2]     # no. of units in each layer
    m = 3     # no. of samples
    learning_rate = 0.5
    no_iter = 10000
    X = np.random.rand(layer_dims[0],m)      # Input set across m samples
    Y = np.random.rand(layer_dims[-1],m)      # Desired output across m samples
    (W, b) = initialize_param(layer_dims)
#     (X,W,b,Y) = test_init()     # Initialize with https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/ 
    display_init (X, Y, layer_dims, m, learning_rate, no_iter, W, b)     # Print out initialized parameters
    
    for iter in range(no_iter):
        ##### Forward Propagation #####
        (Z,A) = forward_prop (X, W, b, Y, layers=(len(layer_dims)-1))

        ##### Calculate Cost #####
#         cost = cost_func(A[-1],Y,m,cf_type='cross_entropy')
        cost = cost_func(A[-1],Y,m,cf_type='sq_err')
#         print ('Cost = {}'.format(cost))

        ##### Back Propagation #####
        (dW, db) = back_prop(A,Y,m,layers=(len(layer_dims)-1))
        
        ##### Adjust Weights
        (W, b) = adjust_weights_bias(W, b, dW, db, learning_rate)

#     print ('Adjusted weights = {}'.format(W))
#     print ('Adjusted bias = {}'.format(b))
    print ('Cost = {}'.format(cost))
    print ('Output = {}'.format(A[-1]))
######################################################
 
if __name__== "__main__":
    main()

--------------------------------------
Desired output matrix Y[2x3] =
 [[0.126 0.207 0.051]
 [0.441 0.03  0.457]]
--------------------------------------
Cost = 0.03998670504863828
Output = [[0.118 0.14  0.125]
 [0.363 0.245 0.324]]


In [89]:
from PIL import Image
import numpy as np
 
img = Image.open("../data_misc/IMG_2053.JPG")
arr = np.array(img)

print (arr.shape)
print ('---------')
print ('# of pixels = ', arr.shape[0]*arr.shape[1])
print ('First pixel @ (0,0) = ', arr[0,0])
print ('Last pixel @ (767, 1023) = ', arr[767,1023])
print ('---------')
arr_flat = arr.reshape(1,-1)
print ('#########')
print ('---------')
# print ('Red = {}'.format(arr[:,:,0]))
# print ('Green = {}'.format(arr[:,:,1]))
# print ('Blue = {}'.format(arr[:,:,2]))

(768, 1024, 3)
---------
# of pixels =  786432
First pixel @ (0,0) =  [215 218 223]
Last pixel @ (767, 1023) =  [163 152 148]
---------
#########
---------
